### ISSUE TITLE
training on pascal

### ISSUE THREAD

**Issue by feixue94** [Junyi42/GeoAware-SC#10]
Hi, 
Thanks for sharing the great work.
In the pascal dataset, there is no file called 'train_pairs_pf_pascal.csv' which is used for training on pascal.
Could u please have a look?

Best

**Comment by feixue94** [comment]
it is solved.

**Comment by Junyi42** [comment]
Glad to know it's solved! For anyone else who has the same issue. 


It's in the 6th line of https://github.com/Junyi42/GeoAware-SC/blob/master/data%2Fprepare_pfpascal.sh or simply download via https://drive.google.com/uc?id=111tpXshLiJ4qudBHoGK3HbMSNr9vVRq9
