### ISSUE TITLE
The annotation of the keypoint subgroups will be released?

### ISSUE THREAD

**Issue by lfz-5** [Junyi42/GeoAware-SC#2]
Hello! Very impressive work, and I wonder if there is a timetable about the release of the annotation of the keypoint subgroups? Thanks a lot!
![2024-04-03 16-27-27 的屏幕截图](https://github.com/Junyi42/GeoAware-SC/assets/43802521/ab69f1cb-58ce-47eb-9961-953c272fb1a6)

**Comment by Junyi42** [comment]
Hi,

Thanks so much for your interest in our work!

The annotation of keypoint subgroups for SPair-71k is here: https://github.com/Junyi42/GeoAware-SC/blob/master/utils/utils_geoware.py#L6; and here for AP-10k: https://github.com/Junyi42/GeoAware-SC/blob/master/utils/utils_geoware.py#L45.

You could search for `args.COMPUTE_GEOAWARE_METRICS` in [pck_train.py](pck_train.py) to see how we use the annotation to compute the metric.

Best,
Junyi

**Comment by lfz-5** [comment]
Thank you very much! I will check the code. Have a good day~
