### ISSUE TITLE
Missing instructions in suggested installation for segment anything

### ISSUE THREAD

**Issue by ehedlin** [Junyi42/GeoAware-SC#3]
Missing installation instructions for segment anything. Should include: `pip install git+https://github.com/facebookresearch/segment-anything.git`

missing file sam_vit_h_4b8939.pth for segment anything [(installed here)](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth)

README says pre extracting instance masks is optional but `python pck_train.py --config configs/train_ap10k.yaml` fails without it

**Comment by ehedlin** [comment]
It seems these are written as comments within `preprocess_mask_sam.py` however it might be easier if it's more explicitly written in the README

**Comment by Junyi42** [comment]
Hi @ehedlin,

Thanks so much for your valuable feedback! I will update the instructions in the README file.

By the way, could you please share a bit more about how exactly `python pck_train.py --config configs/train_ap10k.yaml` fails without the masks? I would like to update the code to make it free with masks. Thanks!

Best,
Junyi

**Comment by ehedlin** [comment]
By default `pck_train.py` fails without masks because it calls (get_distance)[https://github.com/Junyi42/GeoAware-SC/blob/0500595884fee7bb44545bafa98ff8ef5142fc3c/utils/utils_correspondence.py#L22] however I see now that the option `args.MUTUAL_NN` if True avoids that function. It might be helpful to have a little explanation for this as well

**Comment by ehedlin** [comment]
I apologize, I meant to say it fails with the command `python pck_train.py --config configs/eval_zero_shot_spair.yaml` which I see already mentions it fails without masks.
