### ISSUE TITLE
Preprocessing masks for PF-Pascal

### ISSUE THREAD

**Issue by ehedlin** [Junyi42/GeoAware-SC#5]
I am having problems preprocessing segmentation masks for PF-Pascal. `python preprocess_map.py ./data/PF-Pascal/JPEGImages` doesnt work due to getting masks assuming the annotations are json files as opposed to .mat which they are. The images look tightly cropped though. Do you have the code you used to find segmentation masks for this dataset?

**Comment by Junyi42** [comment]
Hi @ehedlin,

PF-Pascal is a special dataset that all the image pairs are already of the same pose and therefore, there is no need to align the pose. In our experiment, we found turning on adaptive pose alignment achieves similar (and sometimes slightly worse) results. Therefore, I would suggest setting `ADAPT_FLIP: false` for the PF-Pascal dataset, and thus there is no need to get the segmentation masks.

**Comment by ehedlin** [comment]
Sounds good, thank you :)
