### ISSUE TITLE
About which layer feature is used

### ISSUE THREAD

**Issue by XLechter** [Junyi42/GeoAware-SC#6]
Hi, thanks for sharing the codes and sorry to bother again.

I am confused about which layers the features s2, s3, s4, and s5 refer to. Do they refer to layers 2, 5, 8, and 11? I print the shape of features s3, s4, s5 (torch.Size([1, 960, 60, 60]) torch.Size([1, 1920, 30, 30]) torch.Size([1, 2560, 15, 15])), but I see you mentioned the feature is 1280 + 960 +480 = 2720. So I am very confused about this, could you kindly explain this? 

Thank you so much.

**Comment by Junyi42** [comment]
Hi,

If you turn on the `decoder_only`, the dimensions of feature s3, s4, s5, should be 480 (layer8), 960 (layer5), and 1280 (layer2) respectively. And if you turn it off (which I assume it might be your case), the dimensions will double since there's an additional encoder layer features, which is just the same size as decoder features.

I would suggest setting the `decoder_only` as ture (which is also our default setting) since our released aggregation network is trained with this setting. Feel free to let me know if this solve your question. Thanks!

**Comment by XLechter** [comment]
@Junyi42 Thank you so much for your reply.

Another question is, could I choose the other layer features? For example, if I want to obtain the 6th layer feature of SD, which part of the codes should I modify?

Thanks again for your time.

**Comment by Junyi42** [comment]
Hi,

I have not tried for the current version, but changing the `block_indices` tuple here https://github.com/Junyi42/GeoAware-SC/blob/92bb7f777c034973d9e0f2a2c834ff3cc5aba2da/model_utils/extractor_sd.py#L163 might work.

If not, I could send you a private repo (though pretty rough) for offline extracting features of different layers of the Stable Diffusion model.

**Comment by XLechter** [comment]
@Junyi42 Thanks for your reply. I tried using different **block_indices** but tensor shape mismatch error occurs in **process_features_and_mask**. It would be nice if you could send me the scripts. My mail is wenxxiao.zhang@gmail.com. Thanks a lot!

**Comment by Junyi42** [comment]
Sent! Feel free to contact me if you have any issues.

**Comment by XLechter** [comment]
Well received. Thank you so much!

**Comment by anas-zafar** [comment]
Hi @Junyi42, can you please share 

> private repo (though pretty rough) for offline extracting features of different layers of the Stable Diffusion model.

this with me as well. Thanks

**Comment by anas-zafar** [comment]
@XLechter were you able to test this out?

**Comment by Junyi42** [comment]
> Hi @Junyi42, can you please share
> 
> > private repo (though pretty rough) for offline extracting features of different layers of the Stable Diffusion model.
> 
> this with me as well. Thanks

Sure, please send me an email at junyizhang@berkeley.edu. Thanks.
