### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by flyindulger** [Junyi42/GeoAware-SC#7]
Hi, great work!
I have a question when I'm running the code of demo, which seems to take ~30GB gpu memory. I am wondering if there is any method to reduce the memory cost? Thank you!

**Comment by Junyi42** [comment]
Hi @flyindulger,

Thanks for your interest in our work!

May I kindly ask what environment setup you are working on? I tested on two machines, and the [notebook demo](https://github.com/Junyi42/GeoAware-SC/blob/master/get_processed_feat.ipynb) was able to fit in single RTX3090/A5000 with 24GB VRAM. The peak memory consume should be around 18GB (10.5GB after loading the model, 16.5GB when extracting features, 17.5GB when computing point matching).

![image](https://github.com/Junyi42/GeoAware-SC/assets/90844802/49da51c4-ef75-41c8-8203-8da2d5d42bfd)

**Comment by Junyi42** [comment]
Hi @flyindulger,

Thanks for the additional information, could you please try `pip install xformers==0.0.16`? The problem should be solved with xformers. Please let me know if it works, thanks!

**Comment by flyindulger** [comment]
It works! Thanks for your help!

**Comment by Junyi42** [comment]
Great to hear that! 😀
