### ISSUE TITLE
Problem in (Pre-)Training on the AP-10k dataset

### ISSUE THREAD

**Issue by Mofafa** [Junyi42/GeoAware-SC#8]
Hi, Thanks for your great work!

When I run "python pck_train.py --config configs/train_ap10k.yaml", I got 
`
  File "$MyPath/GeoAware-SC/pck_train.py", line 354, in eval
    pck, correct_geo, out_results, img_correct = compute_pck(args, *compute_args, thresholds=thresholds) if args.BBOX_THRE else compute_pck(args, *compute_args)

  File "$MyPath/GeoAware-SC/pck_train.py", line 179, in compute_pck
    single_bbox_size = thresholds[pair_idx].repeat(vis.sum()).cpu()
IndexError: index 0 is out of bounds for dimension 0 with size 0
`

It seems when we load the 'val' split in ap10k using `load_apk10k_data`, `thresholds` remain an empty list and args.BBOX_THRE=True. Should we change `thresholds` to be None when pretraining or use the same threshold setting as the 'test' split?

Besides, I am not sure if there are some missing code lines that are used for skipping "cheetah king", "argali", and "black bear" categories in the 'val' split as the paper description.

**Comment by Junyi42** [comment]
Hi,

Thanks so much for pointing out this problem!

I just updated the [commit](https://github.com/Junyi42/GeoAware-SC/commit/ff61cb91147c461e9e293af1fff86e1c18af0347) for this problem. I actually used the "test" set of AP10K for pretraining, and forgot to update the code when publishing it. The result should be similar as using the "val" set, but you could also try to switch to "test" set [here](https://github.com/Junyi42/GeoAware-SC/blob/master/pck_train.py#L339) if only for pretraining.

Please feel free to let me know if you have any further questions!

**Comment by Mofafa** [comment]
That's great! Thanks for your quick response!
