### ISSUE TITLE
Problem in eval ap10k, KeyError: 'azimuth_id'

### ISSUE THREAD

**Issue by wzhlearning** [Junyi42/GeoAware-SC#9]
Thank you for your work! I encountered an issue when evaluating ap10k (loading eval_ap10k.yaml) using pck_train.py. Keyword errors occurred at the end of the evaluation.

Traceback (most recent call last):
  File "/GeoAware-SC/pck_train.py", line 504, in <module>
    main(args)
  File "/GeoAware-SC/pck_train.py", line 446, in main
    _,_,_,result = eval(args, aggre_net, save_path, split='test')
  File "/GeoAware-SC/pck_train.py", line 392, in eval
    if args.COMPUTE_GEOAWARE_METRICS: log_geo_stats(args, geo_aware, geo_aware_count, pcks_geo, pcks_geo_05, pcks_geo_01, weights_geo, kpt_weights, total_out_results)
  File "/GeoAware-SC/utils/logger.py", line 90, in log_geo_stats
    converted_total_results = convert_all_results(total_out_results)
  File "/GeoAware-SC/utils/eval_spair.py", line 133, in convert_all_results
    src_kps, trg_kps, thresholds, src_az, trg_az, mirror = load_spair_data(
  File "/GeoAware-SC/utils/eval_spair.py", line 30, in load_spair_data
    azimuth_src = file["azimuth_id"]
KeyError: 'azimuth_id'

I also couldn't find this keyword in the json files in the ImageAnnotation folder of ap10k. How should I handle it?

**Comment by Junyi42** [comment]
Hi, thanks so much for pointing out the problem!

I think the problem originates from here:
```
File "/GeoAware-SC/utils/logger.py", line 90, in log_geo_stats
converted_total_results = convert_all_results(total_out_results)
```

Could you please update the [line 6](https://github.com/Junyi42/GeoAware-SC/blob/ff61cb91147c461e9e293af1fff86e1c18af0347/utils/logger.py#L6C1-L6C65) from:
```
from utils.eval_spair import get_img_result, convert_all_results
```
to:
```
from utils.eval_spair import get_img_result, convert_all_results, convert_all_results_ap10k
```

And update the [line 90](https://github.com/Junyi42/GeoAware-SC/blob/ff61cb91147c461e9e293af1fff86e1c18af0347/utils/logger.py#L90) from:
```
converted_total_results = convert_all_results(total_out_results)
```
to:
```
converted_total_results = convert_all_results(total_out_results) if args.EVAL_DATASET != "ap10k" else convert_all_results_ap10k(total_out_results)
```

Please kindly let me know if this works, thanks! :-)

**Comment by wzhlearning** [comment]
Thanks! I test it and it work.
